version: '3.9'

services:
  mongodb:
    container_name: gofocused
    image: mongo:latest
    command: mongod --auth
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: